Adding dor docker

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -24,27 +24,18 @@ common:
             which google-chrome
           name: Check browser installed
       - *restore_cache
-      # Step to identify the process using the port
-      - run:
-          name: Identify Process using Port 55556
-          command: |
-            sudo lsof -i :55556 || true
-            # Save the process ID to an environment variable
-            export CONFLICTING_PID=$(sudo lsof -t -i :55556 || true)
-
-      # Step to stop the conflicting process if it exists
-      - run:
-          name: Stop Conflicting Process using port 55556
-          command: |
-            if [ -n "$CONFLICTING_PID" ]; then
-              sudo kill $CONFLICTING_PID
-            fi
       - run:
           name: Docker compose
           command: |
-            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin docker2-granite-release-local.dr-uw2.adobeitc.com
-            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin docker-adobe-cif-release.dr-uw2.adobeitc.com
-            docker-compose -f .circleci/docker-compose.yml up -d
+            set +e  # Disable exit on error
+            for i in $(seq 3); do
+              echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin docker2-granite-release-local.dr-uw2.adobeitc.com
+              echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin docker-adobe-cif-release.dr-uw2.adobeitc.com
+              docker-compose -f .circleci/docker-compose.yml down -v
+              docker-compose -f .circleci/docker-compose.yml up -d && break
+              sleep 10  # Add a delay between retries
+            done
+            set -e  # Enable exit on error
       - attach_workspace:
           at: /home/circleci/build
       - run:
@@ -113,8 +104,6 @@ common:
           name: Cleanup
           command: |
             rm -rf TEST_EXECUTION_STATUS.txt
-            docker-compose -f .circleci/docker-compose.yml down -v
-            docker system prune -af
       # Save test results as artifacts
       - store_artifacts:
           path: ui.tests/test-module/target
